package dac

import "strings"

//go:generate go run ./gen

const sudoersHeader = `# Shipped by the odioctl package — GENERATED by ` + "`go generate ./dac`" + `, do not edit.
# Lets members of the ` + "`odioctl`" + ` group run the privileged bits of odioctl
# unattended:
#   * odio-upgrade.service (systemd --user) applies upgrades as root;
#   * odioctl-web / ` + "`odioctl dac`" + ` rewrite /boot/firmware/config.txt.
# Deliberately not the ` + "`odio`" + ` group: that one carries read/write on
# /var/lib/odio/state.json and odios also puts the installing user in it, so
# keying root on it would turn a state-access group into a root group. odios
# adds only its target user here.
# Every command is spelled out in full (no wildcards) so nothing else — in
# particular no --config PATH — can be passed through sudo.
# XDG_RUNTIME_DIR is kept so the odio_progress callback finds odio-api's upgrade.sock.
Defaults:%odioctl env_keep += "XDG_RUNTIME_DIR"
`

// SudoersFragment renders data/sudoers/odioctl: one explicit line per DAC id,
// no wildcards, so nothing else — in particular no --config PATH — can be
// smuggled through sudo.
func SudoersFragment() string {
	const grant = "%odioctl ALL=(root) NOPASSWD: /usr/bin/odioctl "
	var b strings.Builder
	b.WriteString(sudoersHeader)
	b.WriteString("\n")
	b.WriteString(grant + "upgrade apply --progress\n")
	b.WriteString(grant + "dac unset\n")
	for _, e := range Catalog {
		b.WriteString(grant + "dac set " + e.ID + "\n")
	}
	return b.String()
}
