"""/var/lib/odio/state.json — the record of what odios installed on this box.

Written by odios' ansible post-tasks (write_state.yml) after every install
or upgrade, read by `odioctl upgrade` to derive INSTALL_*/RUN_* for the
next run and edited by `odioctl components` to opt roles/features in or
out. Only the current schema is supported; anything else is a StateError.
"""

from __future__ import annotations

import json
from typing import Any, TypedDict

from odioctl import fsutil

# state.json holds the only non-regenerable bits (roles_excluded,
# features_excluded, release_history, install-time target_user) — lives
# under /var/lib so cache cleanup never wipes it. upgrades.json is a pure
# delta vs the published manifest, regenerated by `odioctl upgrade check`,
# so it stays in /var/cache.
SYSTEM_STATE_PATH = "/var/lib/odio/state.json"
SYSTEM_UPGRADES_PATH = "/var/cache/odio/upgrades.json"


class State(TypedDict):
    """Schema of state.json as written by odios' write_state.yml."""

    odios: str
    install_mode: str
    target_user: str
    roles: dict[str, str]
    roles_excluded: list[str]
    features: list[str]
    features_excluded: list[str]
    release_history: list[str]


_STR_FIELDS = ("odios", "install_mode", "target_user")
_LIST_FIELDS = ("roles_excluded", "features", "features_excluded", "release_history")


class StateError(ValueError):
    """state.json is missing required fields or has the wrong shape."""


def validate_state(data: Any) -> State:
    """Return `data` typed as State, or raise StateError describing the problem."""
    if not isinstance(data, dict):
        raise StateError("state.json must be a JSON object")
    missing = [k for k in (*_STR_FIELDS, "roles", *_LIST_FIELDS) if k not in data]
    if missing:
        raise StateError(f"state.json missing required fields: {', '.join(missing)}")
    for k in _STR_FIELDS:
        if not isinstance(data[k], str) or not data[k]:
            raise StateError(f"state.json field {k!r} must be a non-empty string")
    roles = data["roles"]
    if not isinstance(roles, dict) or not all(
        isinstance(n, str) and isinstance(v, str) for n, v in roles.items()
    ):
        raise StateError("state.json field 'roles' must be an object of {name: version}")
    for k in _LIST_FIELDS:
        if not isinstance(data[k], list) or not all(isinstance(x, str) for x in data[k]):
            raise StateError(f"state.json field {k!r} must be a list of strings")
    return State(
        odios=data["odios"],
        install_mode=data["install_mode"],
        target_user=data["target_user"],
        roles=dict(roles),
        roles_excluded=list(data["roles_excluded"]),
        features=list(data["features"]),
        features_excluded=list(data["features_excluded"]),
        release_history=list(data["release_history"]),
    )


def read_state(path: str) -> State:
    """Load and validate state.json. Raises OSError, json.JSONDecodeError or StateError."""
    with open(path, encoding="utf-8") as f:
        return validate_state(json.load(f))


def write_state_file(path: str, state: State) -> None:
    # Same shape ansible's `to_nice_json` produces (indent 4, sorted keys),
    # so a file rewritten by odioctl diffs cleanly against the next ansible run.
    fsutil.atomic_write_json(path, state, indent=4, sort_keys=True)


def print_state_summary(state: State) -> None:
    roles = ", ".join(sorted(state["roles"].keys())) or "(none)"
    excluded = ", ".join(state["roles_excluded"]) or "(none)"
    features = ", ".join(sorted(state["features"])) or "(none)"
    feat_excluded = ", ".join(state["features_excluded"]) or "(none)"
    print(f"  roles:             {roles}", flush=True)
    print(f"  roles_excluded:    {excluded}", flush=True)
    print(f"  features:          {features}", flush=True)
    print(f"  features_excluded: {feat_excluded}", flush=True)
