// Package state reads and writes /var/lib/odio/state.json — the record of
// what odios installed on this box. Only the current schema is accepted;
// anything else is a *SchemaError.
package state

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/b0bbywan/odioctl/fsutil"
)

// state.json holds the only non-regenerable bits (roles_excluded,
// features_excluded, release_history, install-time target_user) — lives
// under /var/lib so cache cleanup never wipes it. upgrades.json is a pure
// delta vs the published manifest, regenerated by `odioctl upgrade check`,
// so it stays in /var/cache.
const (
	SystemStatePath    = "/var/lib/odio/state.json"
	SystemUpgradesPath = "/var/cache/odio/upgrades.json"
)

// State is the schema of state.json as written by odios' write_state.yml.
type State struct {
	Odios            string            `json:"odios"`
	InstallMode      string            `json:"install_mode"`
	TargetUser       string            `json:"target_user"`
	Roles            map[string]string `json:"roles"`
	RolesExcluded    []string          `json:"roles_excluded"`
	Features         []string          `json:"features"`
	FeaturesExcluded []string          `json:"features_excluded"`
	ReleaseHistory   []string          `json:"release_history"`
}

// SchemaError reports a state.json missing required fields or with the wrong
// shape.
type SchemaError struct{ Reason string }

func (e *SchemaError) Error() string { return e.Reason }

func schemaErrorf(format string, args ...any) error {
	return &SchemaError{Reason: fmt.Sprintf(format, args...)}
}

// Parse decodes and validates state.json content. Pointer fields distinguish
// a missing key from a zero value; the decoder itself rejects wrong shapes.
func Parse(b []byte) (State, error) {
	var raw struct {
		Odios            *string            `json:"odios"`
		InstallMode      *string            `json:"install_mode"`
		TargetUser       *string            `json:"target_user"`
		Roles            *map[string]string `json:"roles"`
		RolesExcluded    *[]string          `json:"roles_excluded"`
		Features         *[]string          `json:"features"`
		FeaturesExcluded *[]string          `json:"features_excluded"`
		ReleaseHistory   *[]string          `json:"release_history"`
	}
	if err := json.Unmarshal(b, &raw); err != nil {
		var ute *json.UnmarshalTypeError
		if errors.As(err, &ute) {
			if ute.Field == "" {
				return State{}, schemaErrorf("state.json must be a JSON object")
			}
			return State{}, schemaErrorf("state.json field %q has the wrong shape (want %s)",
				ute.Field, ute.Type)
		}
		return State{}, err
	}
	var missing []string
	for _, f := range []struct {
		name string
		set  bool
	}{
		{"odios", raw.Odios != nil},
		{"install_mode", raw.InstallMode != nil},
		{"target_user", raw.TargetUser != nil},
		{"roles", raw.Roles != nil},
		{"roles_excluded", raw.RolesExcluded != nil},
		{"features", raw.Features != nil},
		{"features_excluded", raw.FeaturesExcluded != nil},
		{"release_history", raw.ReleaseHistory != nil},
	} {
		if !f.set {
			missing = append(missing, f.name)
		}
	}
	if len(missing) > 0 {
		return State{}, schemaErrorf("state.json missing required fields: %s",
			strings.Join(missing, ", "))
	}
	for name, v := range map[string]string{
		"odios": *raw.Odios, "install_mode": *raw.InstallMode, "target_user": *raw.TargetUser,
	} {
		if v == "" {
			return State{}, schemaErrorf("state.json field %q must be a non-empty string", name)
		}
	}
	return State{
		Odios:            *raw.Odios,
		InstallMode:      *raw.InstallMode,
		TargetUser:       *raw.TargetUser,
		Roles:            *raw.Roles,
		RolesExcluded:    *raw.RolesExcluded,
		Features:         *raw.Features,
		FeaturesExcluded: *raw.FeaturesExcluded,
		ReleaseHistory:   *raw.ReleaseHistory,
	}, nil
}

// Read loads and validates state.json.
func Read(path string) (State, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return State{}, err
	}
	return Parse(b)
}

// Write rewrites state.json in the shape ansible's to_nice_json produces
// (indent 4, sorted keys), so it diffs cleanly against the next ansible run.
func Write(path string, st State) error {
	return fsutil.AtomicWriteJSON(path, st.sortedMap())
}

// sortedMap gives AtomicWriteJSON a map (keys marshal sorted) with no nil
// slice — nil would serialize as null, which Parse rejects on read-back.
func (st State) sortedMap() map[string]any {
	roles := st.Roles
	if roles == nil {
		roles = map[string]string{}
	}
	return map[string]any{
		"odios":             st.Odios,
		"install_mode":      st.InstallMode,
		"target_user":       st.TargetUser,
		"roles":             roles,
		"roles_excluded":    emptyIfNil(st.RolesExcluded),
		"features":          emptyIfNil(st.Features),
		"features_excluded": emptyIfNil(st.FeaturesExcluded),
		"release_history":   emptyIfNil(st.ReleaseHistory),
	}
}

func emptyIfNil(s []string) []string {
	if s == nil {
		return []string{}
	}
	return s
}

// PrintSummary writes the four component lists, one per line.
func PrintSummary(w io.Writer, st State) {
	roles := make([]string, 0, len(st.Roles))
	for n := range st.Roles {
		roles = append(roles, n)
	}
	sort.Strings(roles)
	features := append([]string{}, st.Features...)
	sort.Strings(features)
	fmt.Fprintf(w, "  roles:             %s\n", orNone(roles))
	fmt.Fprintf(w, "  roles_excluded:    %s\n", orNone(st.RolesExcluded))
	fmt.Fprintf(w, "  features:          %s\n", orNone(features))
	fmt.Fprintf(w, "  features_excluded: %s\n", orNone(st.FeaturesExcluded))
}

func orNone(items []string) string {
	if len(items) == 0 {
		return "(none)"
	}
	return strings.Join(items, ", ")
}
