#!/usr/bin/env python3
"""Generate data/sudoers/odioctl from the DAC catalog.

One explicit `dac set <id>` line per catalog entry — no wildcard, so a member
of the `odio` group cannot smuggle `--config /etc/passwd` (or anything else)
past sudo. Re-run after editing dac.CATALOG; tests/test_sudoers.py fails on
drift.

Usage: gen-sudoers.py [--check]
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from odioctl import dac  # noqa: E402

OUT = ROOT / "data" / "sudoers" / "odioctl"
BIN = "/usr/bin/odioctl"

HEADER = """\
# Shipped by the odioctl package — GENERATED by scripts/gen-sudoers.py, do not edit.
# Lets members of the `odio` group (the odios target user) run the privileged
# bits of odioctl unattended:
#   * odio-upgrade.service (systemd --user) applies upgrades as root;
#   * odioctl-web / `odioctl dac` rewrite /boot/firmware/config.txt.
# Every command is spelled out in full (no wildcards) so nothing else — in
# particular no --config PATH — can be passed through sudo.
# XDG_RUNTIME_DIR is kept so the odio_progress callback finds odio-api's upgrade.sock.
Defaults:%odio env_keep += "XDG_RUNTIME_DIR"
"""


def render() -> str:
    lines = [HEADER]
    lines.append(f"%odio ALL=(root) NOPASSWD: {BIN} upgrade apply --progress")
    lines.append(f"%odio ALL=(root) NOPASSWD: {BIN} dac unset")
    for entry in dac.CATALOG:
        lines.append(f"%odio ALL=(root) NOPASSWD: {BIN} dac set {entry.id}")
    return "\n".join(lines) + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date — run scripts/gen-sudoers.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
